config/routes.rb
Rails.application.routes.draw do
  root :to => "users#index"
  resources :users do
    resources :products
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_user

  # GET /products
  # GET /products.json
  def index
    @products = @user.products
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @products }
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product=@user.products.find(params[:id])
  end

  # GET /products/new
  def new
    @user=User.find(params[:user_id])
    @product = @user.products.new
  end

  # GET /products/1/edit
  def edit
    @product=@user.products.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @user=User.find(params[:user_id])
    @product = @user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to user_products_path(@user), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product=@user.products.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to user_products_path(@user), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product=@user.products.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to user_products_path(@user), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :weight, :price, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sidebar.erb
<nav class="navbar navbar-default sidebar" role="navigation">
  <%if @user && @user.id%>
    <%=render "layouts/sidebar_userview", object:@user%>
  <%else%>
    <li class="active list-unstyled text-center">
      <button class="btn btn-primary btn-block">
        <%= link_to "Home", users_path%>
        <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span>
      </button>
    </li>
  <%end%>
</nav>

app/views/layouts/_sidebar_userview.erb
<li class="active list-unstyled text-center">
  <button class="btn btn-primary btn-block">
    <%= link_to "Profile", user_path(object)%><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span>
  </button>
</li>
<li class="list-unstyled text-center">
  <button class="btn btn-success btn-block">
    <%= link_to "My Products", user_products_path(object.id)%><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-apple white-button-text"></span>
  </button>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabAssignment8Cdiazarze</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          <%=render 'layouts/sidebar'%>
        </div>
        <div class="col-sm-10">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for([@user,@product]) do |form| %>

  <div class="row form-group">
    <div class="col-sm-3">
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-sm-3">
      <%= form.label :weight %>
      <%= form.number_field :weight, class:"form-control"  %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-sm-3">
      <%= form.label :price %>
      <%= form.number_field :price, class:"form-control"  %>
    </div>
  </div>

  <div class="row form-group">
    <div class="actions">
      <%= form.submit class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', user_product_path(@user,@product), class:"btn btn-success" %>
<%= link_to 'Back', user_products_path(@user), class:"btn btn-primary" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-responsive table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Price</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.weight %></td>
        <td><%= product.price %></td>
        <td><%= product.user.username %></td>
        <td><%= link_to 'Show', user_product_path(@user, product), class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_user_product_path(@user,product), class:"btn btn-warning"%></td>
        <td><%= link_to 'Destroy', user_product_path(@user, product), class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_user_product_path(@user) , class:"btn btn-success"%>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form'%>

<%= link_to 'Back', user_products_path(@user), class:"btn btn-primary"%>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1><span class="glyphicon glyphicon-apple"> Product <%= @product.name %></span></h1><br>


<div class="row ">
  <div class="col-sm-3 col-md-3 ">
    <div class="field">
      <h4><strong>Name </strong></h4>
      <%= @product.name %>
    </div>
  </div>
  <div class="col-sm-3 col-md-3 ">
    <div class="field">
      <h4><strong>Weight </strong></h4>
      <%= @product.weight %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-3 col-md-3 ">
    <div class="field">
      <h4><strong>Price </strong></h4>
      <%= number_to_currency @product.price %>
    </div>
  </div>
  <div class="col-sm-3 col-md-3 ">
    <div class="field">
      <h4><strong>User </strong></h4>
      <%= @product.user.username%>
    </div>
  </div>
</div>



<%= link_to 'Edit', edit_user_product_path(@user,@product), class:"btn btn-warning" %>
<%= link_to 'Back', user_products_path(@user), class:"btn btn-primary" %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-sm-3">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class:"form-control" %>
    </div>
  </div>

  <div class="row field form-group">
    <div class="col-sm-3">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class:"form-control" %>
    </div>
  </div>

  <div class="row field form-group">
    <div class="col-sm-3">
      <%= form.label :username %>
      <%= form.text_field :username, class:"form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/users/_partial_index.erb
<table class="table table-responsive table-striped">
  <thead>
  <tr>

    <th>First name</th>
    <th>Last name</th>
    <th>Username</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td class="align_middle"><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td class="usuario" id="<%=user.id.to_s%>"><%= user.username %></td>
      <td class="white-button-text"><%= link_to 'Show', user, class:"btn btn-primary white-button-text" %></td>
      <td><%= link_to 'Edit', edit_user_path(user),class:"btn btn-warning white-button-text" %></td>
      <td><%= link_to 'Destroy', user,class:"btn btn-danger white-button-text", method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>
<div class="ex2" id="example">
<li id="ex3">

</div>


<script>

    $(".usuario").click(function () {
        $.get('/users/'+ this.id +'/products.json', function(data){
            $.each(data, function(i , obj){
                console.log(obj)
                $("#example").append($("#ex3").html("Name: "+obj.name+"</li> <li> Weight: "+obj.weight+"</li> <li> Price: "+obj.price+"</li>"));

            });
            });
        });



</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>


<%= link_to 'Go to Profile', @user, class:"btn btn-primary" %>
<%= link_to 'Go to all Users', users_path, class:"btn btn-primary" %>

app/views/users/index.html.erb
<p><%=notice %></p>

<h1 class="text-center"><span class="glyphicon glyphicon-user"> Users</span></h1><br>

<%=render "users/partial_index"%>
<%= link_to 'New User', new_user_path, class:"btn btn-success white-button-text" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
  <p id="notice"><%= notice %></p>

  <h1 class="text-center"><span class="glyphicon glyphicon-user"> <%= @user.first_name%> <%= @user.last_name %></span></h1><br>

  <div class="row">
    <div class="col-sm-3 col-md-3 ">
      <div class="field">
        <h3><strong>Username </strong> </h3>
        <%= @user.username %>
      </div>
    </div>
  </div>


  <%= link_to 'Edit', edit_user_path(@user), class:"btn btn-warning" %>
  <%= link_to 'Go to all Users', users_path, class:"btn btn-primary" %>